<script type='text/javascript'>
Global.ticker = '<?php echo $company_data['ticker'];?>';
Global.house = '<?php echo $company_data['house'];?>';
</script>

<div class="row company-overview-body">
    <div class="text-left">
        <a href="../company/list?industry=<?php echo $company_data['industry_id'];?>">
        <?php echo $company_data['industry']['name']?>&nbsp;
        </a>
        |&nbsp;
        <a href="../company/list?industry=<?php echo $company_data['industry_id'];?>&subindustry=<?php echo $company_data['subindustry_id']?>">
        <?php echo $company_data['subindustry']['name'];?>
        </a>
    </div>
    <div class="small-3 columns no-padding">
        <div>
            <span class="company-overview-name"><?php echo $company_data['name'];?></span>
            <span class="company-overview-code"><?php echo $company_data['ticker'].'.'.$company_data['house'];?></span>
        </div>
        <div class="company-overview-price">
            <span class="small-3 no-padding" id="price_now"></span>
            <span class="small-3 no-padding" id="price_diff"></span>
            <span class="small-3 no-padding" id="price_rate"></span>
        </div>
    </div>
    <div class="small-3 columns no-padding company-overview-title">
        <div>
            <span>成交量</span>
            <span id="volumn_now">--</span>
        </div>
        <div>
            <span>成交额</span>
            <span id="count_now">--</span>
        </div>
    </div>
    <div class="small-3 columns no-padding company-overview-title">
        <div>
            <span>总市值</span>
            <span><?php echo sprintf('%.2f',$company_data['market_cup']);?>亿</span>
        </div>
        <div>
            <span>市盈率TTM</span>
            <span><?php echo sprintf('%.2f',$company_data['ttm']);?></span>
        </div>
    </div>
    <div class="small-3 columns no-padding company-overview-title">
        <div>
            <span>近期披露</span>
            <span><?php echo $company_data['report_year'].$company_data['report_type'];?></span>
        </div>
        <div>
            <span>披露日期</span>
            <span><?php echo $company_data['release_date'];?></span>
        </div>
    </div>
</div>

<div class="row company-nav-body">
    <span class="actived">概况</span>
    <span id="chart_nav_2">财务指标</span>
    <span>收入利润</span>
    <span>资产负债</span>
    <span>现金流量</span>
    <span>杜邦分析</span>
    <a href="http://www.cninfo.com.cn/information/companyinfo_n.html?fulltext?<?php echo strtolower($company_data['house']).'mb'.$company_data['ticker'];?>" target='_blank'>
        <span>公司公告</span>
    </a>
</div>

<div class="row company-chart-body" id="chart_body_1"></div>
<div class="row company-chart-body" id="chart_body_2"></div>
<div class="row company-chart-body" id="chart_body_3"></div>
<div class="row company-chart-body" id="chart_body_4"></div>
<script src="../js/company_detail.js" type="text/javascript"></script>
