<script type='text/javascript'>
Global.ticker = '<?php echo $company_data['ticker'];?>';
</script>

<div class="row company-overview-body">
    <div class="text-left"><?php echo $company_data['industry']['name']?>&nbsp;|&nbsp;<?php echo $company_data['subindustry']['name'];?></div>
    <div class="small-3 columns no-padding">
        <div>
            <span class="company-overview-name"><?php echo $company_data['name'];?></span>
            <span class="company-overview-code"><?php echo $company_data['ticker'].'.'.$company_data['house'];?></span>
        </div>
        <div class="company-overview-price">
            <span class="small-3 no-padding">13.45</span>
            <span class="small-3 no-padding">+0.22</span>
            <span class="small-3 no-padding">+1.66%</span>
        </div>
    </div>
    <div class="small-3 columns no-padding company-overview-title">
        <div>
            <span>成交量</span>
            <span>2036.38万股</span>
        </div>
        <div>
            <span>成交额</span>
            <span>2.70亿</span>
        </div>
    </div>
    <div class="small-3 columns no-padding company-overview-title">
        <div>
            <span>总市值</span>
            <span>807.22亿</span>
        </div>
        <div>
            <span>市盈率TTM</span>
            <span>20.22</span>
        </div>
    </div>
    <div class="small-3 columns no-padding company-overview-title">
        <div>
            <span>近期披露</span>
            <span>15Q4</span>
        </div>
        <div>
            <span>披露日期</span>
            <span>2016-3-1</span>
        </div>
    </div>
</div>

<div class="row company-nav-body">
    <span class="actived">概况</span>
    <span id="chart_nav_2">财务指标</span>
    <span>收入利润</span>
    <span>资产负债</span>
    <span>现金流量</span>
    <span>杜邦分析</span>
</div>

<div class="row company-chart-body" id="chart_body_1">
</div>

<script src="../js/company_detail.js" type="text/javascript"></script>
