      <div class="back-color-1 company-content-body">
         <div class="row back-color-white ">
            <div class="back-color-white index-cal-title">
                <div class="row"><div class="small-6 small-centered columns"><div class="row">
                    <div class="small-4 index-cal-title-box columns">
                        <div class="company-cal-title-innerbox">
                            <div>沪深</div>
                        </div>
                    </div>
                    <div class="small-4 index-cal-title-box columns">
                        <div class="company-cal-title-innerbox">
                            <div>香港</div>
                        </div>
                    </div>
                    <div class="small-4 index-cal-title-box columns">
                        <div class="company-cal-title-innerbox">
                            <div>美国</div>
                        </div>
                    </div>
                </div></div></div>
                <div class="row">
                  <div class="small-10 small-offset-1 columns"><div class="row">
                  <div class="page-divider-2"></div>
                  <div class="row">
                      <div class="small-2 columns">
                          <div class="company-cal-title-innerbox">
                              <div>全部行业</div>
                          </div>
                      </div>
                      <div class="small-2 columns">
                          <div class="company-cal-title-innerbox">金融</div>
                          <div class="company-cal-title-innerbox">工业</div>
                      </div>
                      <div class="small-2 columns">
                          <div class="company-cal-title-innerbox">消费</div>
                          <div class="company-cal-title-innerbox">材料</div>
                      </div>
                      <div class="small-2 columns">
                          <div class="company-cal-title-innerbox">科技</div>
                          <div class="company-cal-title-innerbox">能源</div>
                      </div>
                      <div class="small-2 columns">
                          <div class="company-cal-title-innerbox">医疗保健</div>
                          <div class="company-cal-title-innerbox">公共事业</div>
                      </div>
                      <div class="small-2 columns">
                          <div class="company-cal-title-innerbox">服务</div>
                          <div class="company-cal-title-innerbox">综合企业</div>
                      </div>
                  </div>
                </div></div>
                <div class="small-1 columns"><span class="question_mark">?</span></div>
            </div>
            </div>
      </div>
      <div class="company-list-table-body row">
            <table class="company-list-table" cellpadding="0" cellspacing="0" >
              <tbody>
              <tr>
                <th>代码</th>
                <th>股票简称</th>
                <th>行业</th>
                <th>市值</th>
                <th>市盈率</th>
                <th>股价</th>
                <th>涨跌幅</th>
                <th>成交额</th>
              </tr>
              <?php for($i=0;$i<20;$i++): ?>
                <tr>
                  <td><a href="../company/detail">股票a</a></td>
                  <td>股票a</td>
                  <td>股票a</td>
                  <td>股票a</td>
                  <td>股票a</td>
                  <td>股票a</td>
                  <td>股票a</td>
                  <td>股票a</td>
                </tr>
             <?php endfor; ?>
             </tbody>
            </table>
     </div>
     <div class="company-list-table-bottom row">
        <div class="small-4 columns company-list-table-bottom-1">每页显示股票数量 20 | 50</div>
        <div class="small-4 columns company-list-table-bottom-2">&lt;&nbsp;<input value=1 /> of 100&nbsp;&gt;</div>
        <div class="small-4 columns company-list-table-bottom-3">生成Excel</div>
     </div>
</div>
