<div class="row">
    <div class="index-industry-seletor">
        <div class="small-2 left columns">行业:&nbsp;<span class="index-industry-list-title" type="button" id="industry_title" data-toggle="industry_dropdown">全部&nbsp;&#9660;</span></div>
        <div class="small-4 left columns">子行业:&nbsp;<span class="index-industry-list-title" type="button" id="subindustry_title" data-toggle="subindustry_dropdown">全部&nbsp;&#9660;</span></div>
        <div class="small-4 right columns" style="text-align:right"><input type='checkbox' id="flag_checkbox"/>&nbsp;仅包括沪深300指数成分股</div>
    </div>
    <div class="dropdown-pane bottom index-industry-list" id="industry_dropdown" data-dropdown >
        <ul>
            <li id="industry_list_all" sid="all" sub='[{}]'>全部</li>
            <?php foreach($industry_data as $key=>$value): ?>
            <li class="industry_list_select" sid="<?php echo $value['id'];?>" sub='<?php echo json_encode($value['sub']);?>'><?php echo $value['name'];?></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="dropdown-pane index-industry-list" id="subindustry_dropdown" data-dropdown >
        <ul id="subindustry_list">
            <li class="subindustry_list_select" sid="all">全部</li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="index-table-block" id="ajax_report_list">
        <!-- ajax load data: data/report.phtml -->
    </div>
    <div class="company-table-loading" id="ajax_loader">
        <img class="ajax-loader" src="../images/ajax-loader.gif" />
    </div>
</div>
<script type='text/javascript'>
    Global.industry = <?php echo $industry_id?$industry_id:'"all"';?>;
    Global.subindustry = <?php echo $subindustry_id?$subindustry_id:'"all"';?>;
</script>
<script src="../js/company.js" type='text/javascript'></script>
