    var myChart = echarts.init(document.getElementById('<?php echo $divId;?>'));
    var option = {
        backgroundColor:'#353535',
        textStyle: {
            color:'#ccc',
        },
        color:["#D42826","#9564BD","#349B2E","#FE7F0E","#1F78B4","#555"],
        title: {
            text: '成本结构',
            textStyle: {
                color:'#ccc',
            },
        },
        tooltip: {},
        grid: {
        },
        legend: {
            data:['净利润','成本','销售、行政及一般费用','所得税','其他费用支出'],
            textStyle: {
                color:'#ccc',
            },
        },
        xAxis: {
            data: ["13Q1","13Q2","13Q3","13Q4",
                   "14Q1","14Q2","14Q3","14Q4",
                   "14Q1","14Q2","14Q3","14Q4",],
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                }
            },
            splitLine: {
                lineStyle: {
                    color: ['#555']
                }
            },
        },
        yAxis:[
        {
            type:'value',
            name:'CNY百万',
            splitNumber:'5',
            splitLine: {
                lineStyle: {
                    color: ['#555']
                }
            },
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                }
            },
            scale:true,
        }],
        series: [
        {
            name: '其他费用支出',
            type: 'bar',
            stack:'1',
            data: [20, 30, 36, 50, 
                   40,70, 28, 30,
                   40,70, 28, 30]
        },
        {
            name: '所得税',
            type: 'bar',
            stack:'1',
            data: [50, 40, 76, 70, 
                   90,150, 128, 90,
                   90,150, 128, 90,]
        },
        {
            name: '销售、行政及一般费用',
            type: 'bar',
            stack:'1',
            data: [20, 30, 36, 50, 
                   40,70, 28, 30,
                   40,70, 28, 30]
        },
        {
            name: '成本',
            type: 'bar',
            stack:'1',
            data: [20, 30, 36, 50, 
                   40,70, 28, 30,
                   40,70, 28, 30]
        },
        {
            name: '净利润',
            type: 'bar',
            stack:'1',
            data: [100, 200, 160, 200, 
                   300,200, 180, 200,
                   200,400, 280, 300],

        },
        {
            type:'line',
            name:'总和',
            markLine : {
                data : [
                    [{
                        name: '最高值',
                        value:'760',
                        coord:[0,760],
                    }, {
                        coord:[11,760],
                    }]
                ],
            },
        },
        ],
    };
    myChart.setOption(option);
