    var myChart = echarts.init(document.getElementById('<?php echo $divId;?>'));
    var option = {
        backgroundColor:'#353535',
        textStyle: {
            color:'#ccc',
        },
        color:["#D42826","#349B2E","#FE7F0E","#1F78B4","#555"],
        title: {
            text: '流动资产',
            textStyle: {
                color:'#ccc',
            },
        },
        tooltip: {},
        grid: {
        },
        legend: {
            data:['现金','应收','存货','其他流动资产'],
            textStyle: {
                color:'#ccc',
            },
        },
        xAxis: {
            data: ["13Q1","13Q2","13Q3","13Q4",
                   "14Q1","14Q2","14Q3","14Q4",
                   "14Q1","14Q2","14Q3","14Q4",],
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                }
            },
            splitLine: {
                lineStyle: {
                    color: ['#555']
                }
            },
        },
        yAxis:[
        {
            type:'value',
            name:'CNY百万',
            splitNumber:'5',
            splitLine: {
                lineStyle: {
                    color: ['#555']
                }
            },
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                }
            },
            scale:true,
        }],
        series: [
        {
            name: '其他流动资产',
            type: 'bar',
            stack:'1',
            data: [20, 30, 36, 50, 
                   40,70, 28, 30,
                   40,70, 28, 30]
        },
        {
            name: '存货',
            type: 'bar',
            stack:'1',
            data: [50, 40, 76, 70, 
                   90,150, 128, 90,
                   90,150, 128, 90,]
        },
        {
            name: '应收',
            type: 'bar',
            stack:'1',
            data: [20, 30, 36, 50, 
                   40,70, 28, 30,
                   40,70, 28, 30]
        },
        {
            name: '现金',
            type: 'bar',
            stack:'1',
            data: [100, 200, 160, 200, 
                   300,200, 180, 200,
                   200,400, 280, 300],

        },
        ],
    };
    myChart.setOption(option);
