    var myCharts = echarts.init(document.getElementById('<?php echo $divId;?>'));
    var option = {
        backgroundColor:'#262626',
        textStyle: {
            color:'#ccc',
        },
        color:["#FE7F0E","#1F78B4","#555"],
        title: {
            text: '流动性',
            textStyle: {
                color:'#ccc',
            },
        },
        tooltip: {
            formatter:"{a}<br/>{b}: {c}%",
        },
        grid: {
        },
        legend: {
            data:['流动比率','速动比率'],
            textStyle: {
                color:'#ccc',
            },
        },
        xAxis: {
            data: <?php echo json_encode($xAris);?>,
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                },
            },
            axisLine: {
                onZero:false,
            },
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                },
            },
            boundaryGap:false,
        },
        yAxis:[
        {
            type:'value',
            name:'CNY百万',
            splitNumber:'5',
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                }
            },
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                },
                formatter: '{value}%',
            },
            scale:true,
        }],
        series: [
        {
            name: '速动比率',
            type: 'line',
            showAllSymbol:true,
            data: <?php echo json_encode($data2);?>,
        },
        {
            name: '流动比率',
            type: 'line',
            showAllSymbol:true,
            data: <?php echo json_encode($data1);?>,
        },
        ],
    };
    myCharts.setOption(option);
