<div>
    <span class="chart-type-select <?php echo $graphType=='year'?'actived':'';?>" id="chart_select_loandepositrate_year">年度</span>
    <span>&nbsp;|&nbsp;</span>
    <span class="chart-type-select <?php echo $graphType=='season'?'actived':'';?>" id="chart_select_loandepositrate_season">季度</span>
</div>
<div class="chart-graph" id="chart_loandepositrate"></div>
<div class="chart-div">
    <table class="chart-table" id="chart_table_loandepositrate">
        <tr>
            <th></th>
            <?php foreach($xAris as $value): ?>
            <th>
                <?php echo $value; ?>
            </th>
            <?php endforeach; ?>
        </tr>
        <tr>
            <th toggle-tr="true" toggle-to="line1">贷存比</th>
            <?php foreach($data1 as $value): ?>
            <td><?php echo $value.'%';?></td>
            <?php endforeach; ?>
        </tr>
        <tr class="chart-table-hide" toggle-by="line1">
            <th>贷款</th>
            <?php foreach($hideData1 as $value): ?>
            <td><?php echo $value;?></td>
            <?php endforeach; ?>
        </tr>
        <tr class="chart-table-hide" toggle-by="line1">
            <th>存款</th>
            <?php foreach($hideData2 as $value): ?>
            <td><?php echo $value;?></td>
            <?php endforeach; ?>
        </tr>
        <tr>
            <th toggle-tr="true" toggle-to="line2">贷款/总资产</th>
            <?php foreach($data2 as $value): ?>
            <td><?php echo $value.'%'; ?></td>
            <?php endforeach; ?>
        </tr>
        <tr class="chart-table-hide" toggle-by="line2">
            <th>贷款</th>
            <?php foreach($hideData1 as $value): ?>
            <td><?php echo $value;?></td>
            <?php endforeach; ?>
        </tr>
        <tr class="chart-table-hide" toggle-by="line2">
            <th>总资产</th>
            <?php foreach($hideData3 as $value): ?>
            <td><?php echo $value;?></td>
            <?php endforeach; ?>
        </tr>
        <tr>
            <th toggle-tr="true" toggle-to="line3">存款/总资产</th>
            <?php foreach($data2 as $value): ?>
            <td><?php echo $value.'%'; ?></td>
            <?php endforeach; ?>
        </tr>
        <tr class="chart-table-hide" toggle-by="line3">
            <th>存款</th>
            <?php foreach($hideData2 as $value): ?>
            <td><?php echo $value;?></td>
            <?php endforeach; ?>
        </tr>
        <tr class="chart-table-hide" toggle-by="line3">
            <th>总资产</th>
            <?php foreach($hideData3 as $value): ?>
            <td><?php echo $value;?></td>
            <?php endforeach; ?>
        </tr>
    </table>
</div>
<script type='text/javascript'>
    var loadGraph = function(graphType){
        $("#chart_loandepositrate").html(CompanyDetail.ajaxLoader);
        $.ajax({
            type:"POST",
            url: "../graph/loandepositrate",
            data: {
                "ticker":Global.ticker,
                "graphType":graphType,
                "divId":'<?php echo $divId;?>',
            },
            success: function(result) {
                $('#<?php echo $divId;?>').html(result);
            },
        });
    };
    $('#chart_select_loandepositrate_year').click(function(){
        loadGraph('year');
    });
    $('#chart_select_loandepositrate_season').click(function(){
        loadGraph('season');
    });

    $('#chart_table_loandepositrate .chart-table-hide').hide();
    $('#chart_table_loandepositrate th[toggle-tr="true"]').click(function(){
        var toggleKey = $(this).attr('toggle-to');
        $('#chart_table_loandepositrate .chart-table-hide[toggle-by="'+toggleKey+'"]').toggle();
    });
    var myCharts = echarts.init(document.getElementById('chart_loandepositrate'));
    var option = {
        backgroundColor:'#262626',
        textStyle: {
            color:'#ccc',
        },
        color:["#FE7F0E","#1F78B4","#555"],
        title: {
            text: '贷存比率',
            textStyle: {
                color:'#ccc',
            },
        },
        tooltip: {
            formatter:"{a}<br/>{b}: {c}%",
        },
        grid: {
        },
        legend: {
            data:['贷存比','贷款/总资产','存款/总资产'],
            textStyle: {
                color:'#ccc',
            },
        },
        xAxis: {
            data: <?php echo json_encode($xAris);?>,
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                },
            },
            axisLine: {
                onZero:false,
            },
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                },
            },
            boundaryGap:false,
        },
        yAxis:[
        {
            type:'value',
            name:'%',
            splitNumber:'5',
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                }
            },
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                },
                formatter: '{value}%',
            },
            scale:true,
        }],
        series: [
        {
            name: '贷存比',
            type: 'line',
            showAllSymbol:true,
            data: <?php echo json_encode($data1);?>,
        },
        {
            name: '贷款/总资产',
            type: 'line',
            showAllSymbol:true,
            data: <?php echo json_encode($data2);?>,
        },
        {
            name: '存款/总资产',
            type: 'line',
            showAllSymbol:true,
            data: <?php echo json_encode($data3);?>,
        },
        ],
    };
    myCharts.setOption(option);
</script>
