<div>
    <span class="chart-type-select <?php echo $graphType=='year'?'actived':'';?>" id="chart_select_profitmargin_year">年度报告</span>
    <span>&nbsp;|&nbsp;</span>
    <span class="chart-type-select <?php echo $graphType=='season'?'actived':'';?>" id="chart_select_profitmargin_season">季度报告</span>
</div>
<div class="chart-graph" id="chart_profitmargin"></div>
<script type="text/javascript">
$(function(){
    var loadGraph = function(graphType){
        $("#chart_profitmargin").html(CompanyDetail.ajaxLoader);
        $.ajax({
            type:"POST",
            url: "../graph/profitmargin",
            data: {
                "ticker":Global.ticker,
                "graphType":graphType,
                "divId":'<?php echo $divId;?>',
            },
            success: function(result) {
                $('#<?php echo $divId;?>').html(result);
            },
        });
    };
    $('#chart_select_profitmargin_year').click(function(){
        loadGraph('year');
    });
    $('#chart_select_profitmargin_season').click(function(){
        loadGraph('season');
    });
    var myChart = echarts.init(document.getElementById('chart_profitmargin'));
    var option = {
        backgroundColor:'#262626',
        textStyle: {
            color:'#ccc',
        },
        color:["#349B2E","#FE7F0E","#1F78B4"],
        title: {
            text: '利润率',
            textStyle: {
                color:'#ccc',
            },
        },
        tooltip: {
            formatter:'{a}<br/>{b}: {c}%',
        },
        grid: {
        },
        legend: {
            <?php if($data2): ?>
            data:['净利率','毛利率','经营利润率'],
            <?php else: ?>
            data:['净利率','毛利率'],
            <?php endif; ?>
            textStyle: {
                color:'#ccc',
            },
        },
        xAxis: {
            data: <?php echo json_encode($xAris);?>,
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                },
            },
            axisLine: {
                onZero:false,
            },
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                },
            },
            boundaryGap:false,
        },
        yAxis:[
        {
            type:'value',
            name:'百分比',
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                }
            },
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                },
                formatter: '{value}%',
            },
            scale:false,
        },
        ],
        series: [
        {
            name: '净利率',
            type: 'line',
            showAllSymbol : true,
            data: <?php echo json_encode($data1);?>,
        },
        {
            name: '经营利润率',
            type: 'line',
            showAllSymbol : true,
            data: <?php echo json_encode($data2);?>,
        },
        {
            name: '毛利率',
            type: 'line',
            showAllSymbol : true,
            data: <?php echo json_encode($data3);?>,
        },
        ],
    };
    myChart.setOption(option);
});
</script>
