    var myChart = echarts.init(document.getElementById('<?php echo $divId;?>'));
    var option = {
        backgroundColor:'#262626',
        textStyle: {
            color:'#ccc',
        },
        color:["#349B2E","#FE7F0E","#1F78B4"],
        title: {
            text: '利润率',
            textStyle: {
                color:'#ccc',
            },
        },
        tooltip: {
            formatter:'{a}<br/>{b}: {c}%',
        },
        grid: {
        },
        legend: {
            data:['净利率','毛利率','经营利润率'],
            textStyle: {
                color:'#ccc',
            },
        },
        xAxis: {
            data: <?php echo json_encode($xAris);?>,
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                },
            },
            axisLine: {
                onZero:false,
            },
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                },
            },
            boundaryGap:false,
        },
        yAxis:[
        {
            type:'value',
            name:'百分比',
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                }
            },
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                },
                formatter: '{value}%',
            },
            scale:false,
        },
        ],
        series: [
        {
            name: '净利率',
            type: 'line',
            showAllSymbol : true,
            data: <?php echo json_encode($data1);?>,
        },
        {
            name: '经营利润率',
            type: 'line',
            showAllSymbol : true,
            data: <?php echo json_encode($data2);?>,
        },
        {
            name: '毛利率',
            type: 'line',
            showAllSymbol : true,
            data: <?php echo json_encode($data3);?>,
        },
        ],
    };
    myChart.setOption(option);
