<div>
    <span class="chart-type-select <?php echo $graphType=='year'?'actived':'';?>" id="chart_select_turnoverdays_year">年度</span>
    <span>&nbsp;|&nbsp;</span>
    <span class="chart-type-select <?php echo $graphType=='season'?'actived':'';?>" id="chart_select_turnoverdays_season">季度</span>
</div>
<div class="chart-graph" id="chart_turnoverdays"></div>
<script type="text/javascript">
$(function(){
    var myChart = echarts.init(document.getElementById('chart_turnoverdays'));
    var option = {
        backgroundColor:'#262626',
        textStyle: {
            color:'#ccc',
        },
        color:["#1F78B4","#FE7F0E","#555"],
        title: {
            text: '存货周转',
            textStyle: {
                color:'#ccc',
            },
        },
        tooltip:{},
        legend: {
            data:['存货周转天数','应收周转天数'],
            textStyle: {
                color:'#ccc',
            },
        },
        xAxis: {
            data: <?php echo json_encode($xAris);?>,
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                }
            },
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                }
            },
            boundaryGap:false,
        },
        yAxis:[
        {
            type:'value',
            name:'天数',
            splitLine: {
                show:false,
                lineStyle: {
                    color: ['#555']
                }
            },
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                },
                formatter: '{value}天',
            },
            scale:false,
        },
        ],
        series: [
            {
                name: '存货周转天数',
                type: 'line',
                showAllSymbol : true,
                data: <?php echo json_encode($data1);?>,
            },
            {
                name: '应收周转天数',
                type: 'line',
                showAllSymbol : true,
                data: <?php echo json_encode($data2);?>,
            },
        ],
    };
    myChart.setOption(option);
});
</script>
