<div>
    <span class="chart-type-select <?php echo $graphType=='year'?'actived':'';?>" id="chart_select_turnoverdays_year">年度报告</span>
    <span>&nbsp;|&nbsp;</span>
    <span class="chart-type-select <?php echo $graphType=='season'?'actived':'';?>" id="chart_select_turnoverdays_season">季度报告</span>
</div>
<div class="chart-graph" id="chart_turnoverdays"></div>
<script type="text/javascript">
$(function(){
    var myChart = echarts.init(document.getElementById('chart_turnoverdays'));
    var option = {
        backgroundColor:'#262626',
        textStyle: {
            color:'#ccc',
        },
        color:["#1F78B4","#FE7F0E","#555"],
        title: {
            text: '存货周转',
            textStyle: {
                color:'#ccc',
            },
        },
        tooltip: {},
        grid: {
        },
        legend: {
            data:['存货','存货周转天数'],
            textStyle: {
                color:'#ccc',
            },
        },
        xAxis: {
            data: ["13Q1","13Q2","13Q3","13Q4",
                   "14Q1","14Q2","14Q3","14Q4",
                   "14Q1","14Q2","14Q3","14Q4",],
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                }
            },
            splitLine: {
                lineStyle: {
                    color: ['#555']
                }
            },
        },
        yAxis:[
        {
            type:'value',
            name:'存货(CNY百万)',
            splitNumber:'5',
            splitLine: {
                lineStyle: {
                    color: ['#555']
                }
            },
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                }
            },
            scale:true,
            boundaryGap: ['5%', '5%'],
        },
        {
            type:'value',
            name:'存货周转天数',
            splitLine: {
                lineStyle: {
                    color: ['#555']
                }
            },
            axisTick: {
                lineStyle: {
                    color: '#555'
                }
            },
            axisLabel: {
                textStyle: {
                    color: '#ccc'
                }
            },
            splitLine:{
                show:false,
            },
            scale:true,
            boundaryGap: ['5%', '5%'],
        },
        ],
        series: [
        {
            name: '存货',
            type: 'line',
            stack:'1',
            data: [],
        },
        {
            name: '存货周转天数',
            type: 'line',
            yAxisIndex:'1',
            data: [],
        },
        ],
    };
    myChart.setOption(option);
});
</script>
