<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <?php echo $this->headTitle('减法 - 简单明了看财报'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/icon.png'))
                        ->prependStylesheet($this->basePath('css/style.css'))
			->prependStylesheet($this->basePath('css/foundation.css'))
			->prependStylesheet($this->basePath('css/custom.css'))
	    ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/foundation.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/echarts.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
        <script src="../js/vendor/modernizr.js"></script>
    </head>
    <body>
	<div style="min-width:1000px">
        <div class="layout-topbar">
            <div class="row" style="height:100%">
                <div class="small-2 columns layout-topbar-title">
                    <div>减法</div>
                    <div>简单明了看财报</div>
                </div>
                <a href="#"><div class="small-2 columns layout-topbar-menu left">财报日历</div></a>
                <a href="#"><div class="small-2 columns layout-topbar-menu left">公司</div></a>
                <div class="small-1 columns layout-topbar-wx right">微信群</div>
                <div class="small-4 columns layout-topbar-search right"><input class="right" placeholder="搜索股票代码/公司名" /></div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->

	</div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
