<?php $orderArray = explode(" ",$orderString); ?>
<div>符合条件的股票:&nbsp;<?php echo $total_num; ?>个</div>
    <table class="index-table-list">
        <tbody>
             <tr>
                 <th class="text-left">
                    <a href="javascript:void(0)" order='ticker' <?php echo $orderArray[0]=='ticker'?('orderSelect=1 orderP='.($orderArray[1]=='ASC'?'1':'0')):'';?> class="company_table_order">
                        代码<span><?php echo $orderArray[0]=='ticker'?($orderArray[1]=='ASC'?'&#9650':'&#9660'):'';?></span>
                    </a>
                 </th>
                 <th class="text-left">简称</th>
                 <th>最新价</th>
                 <th>涨跌幅</th>
                 <th>成交额(亿)</th>
                 <th>
                     <a href="javascript:void(0)" order='market_cup' <?php echo $orderArray[0]=='market_cup'?('orderSelect=1 orderP='.($orderArray[1]=='ASC'?'1':'0')):'';?> class="company_table_order">
                        总市值(亿)<span><?php echo $orderArray[0]=='market_cup'?($orderArray[1]=='ASC'?'&#9650':'&#9660'):'';?></span>
                     </a>
                 </th>
                 <th>
                     <a href="javascript:void(0)" order='ttm' <?php echo $orderArray[0]=='ttm'?('orderSelect=1 orderP='.($orderArray[1]=='ASC'?'1':'0')):'';?> class="company_table_order">
                        市盈率(TTM)<span><?php echo $orderArray[0]=='ttm'?($orderArray[1]=='ASC'?'&#9650':'&#9660'):'';?></span>
                     </a>
                 </th>
                 <th>近期披露</th>
                 <th>
                     <a href="javascript:void(0)" order='release_date' <?php echo $orderArray[0]=='release_date'?('orderSelect=1 orderP='.($orderArray[1]=='ASC'?'1':'0')):'';?> class="company_table_order">
                        日期<span><?php echo $orderArray[0]=='release_date'?($orderArray[1]=='ASC'?'&#9650':'&#9660'):'';?></span>
                     </a>
                 </th>
             </tr>
             <?php foreach($report_list as $key=>$value): ?>
             
             <tr>
                 <td class="text-left">
                     <a href='../company/detail?ticker=<?php echo $value['ticker'];?>'><?php echo $value['ticker'].'.'.$value['house']; ?></a>
                 </td>
                 <td class="text-left">
                     <a href='../company/detail?ticker=<?php echo $value['ticker'];?>'><?php echo $value['name'];?></a>
                 </td>
                 <td><?php echo sprintf('%.2f',$value['price_now']);?></td>
                 <td class="<?php echo $value['color']?>"><?php echo $value['price_rate'];?></td>
                 <td><?php echo sprintf('%.2f',$value['volumn']);?></td>
                 <td><?php echo sprintf('%.2f',$value['market_cup']);?></td>
                 <td><?php echo sprintf('%d',$value['ttm']);?></td>
                 <td><?php echo $value['report_year'].$value['report_type'];?></td>
                 <td><?php echo $value['release_date'];?></td>
             </tr>
             <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
    $totalPage = ceil($total_num/$countPerPage);
    $pageSeq = array();
    if($totalPage <= 7) {
        for($i=1;$i<=$totalPage;$i++){
            $pageSeq[$i-1] = $i;
        }
    }
    else {
        if($page <= 3 || $page >= $totalPage - 2) {
            $pageSeq = array(1,2,3,'...',$totalPage-2,$totalPage-1,$totalPage);
        }
        else {
            $pageSeq = array(1,'...',$page-1,$page,$page+1,'...',$totalPage);
        }
    }
    if($page != 'all'):
?>
<div class="company-list-page">
    <ul class="pagination text-center" role="navigation" aria-label="Pagination">
        <?php if($page==1): ?>
        <li class="pagination-previous disabled">上一页</li>
        <?php else: ?>
        <li class="pagination-previous"><a href="javascript:void(0)" id="list_page_pre">上一页</a></li>
        <?php endif; ?>
        <!--<li class="current"><span class="show-for-sr">当前:&nbsp;</span> 1</li>-->
        <?php for($i=0;$i<count($pageSeq);$i++): ?>
        <li>
            <?php if($pageSeq[$i] !='...'):?>
            <a href="javascript:void(0)" class="<?php if($page==$pageSeq[$i])echo "current";?> list_page_num"><?php echo $pageSeq[$i];?></a>
            <?php else: ?>
            ...
            <?php endif; ?>
        </li>
        <?php endfor; ?>
        <?php if($page==$totalPage): ?>
        <li class="pagination-next disabled">下一页</li>
        <?php else: ?>
        <li class="pagination-next"><a href="javascript:void(0)" id="list_page_next">下一页</a></li>
        <?php endif; ?>
    </ul>
</div>
<?php endif; ?>
