<div>符合条件的股票:&nbsp;<?php echo $total_num; ?>个</div>
    <table class="index-table-list">
        <tbody>
             <tr>
                 <th>代码</th>
                 <th>简称</th>
                 <th>最新价</th>
                 <th>涨跌幅</th>
                 <th>成交额(亿)</th>
                 <th>总市值(亿)</th>
                 <th>市盈率</th>
                 <th>近期披露</th>
                 <th>日期</th>
             </tr>
             <?php foreach($report_list as $key=>$value): ?>
             <tr>
                 <td><?php echo $value['ticker'].'.'.$value['house']; ?></td>
                 <td><?php echo $value['name'];?></td>
                 <td><?php echo sprintf('%.2f',$value['price_now']);?></td>
                 <td class="<?php echo $value['color']?>"><?php echo $value['price_rate'];?></td>
                 <td><?php echo sprintf('%.2f',$value['volumn']);?></td>
                 <td><?php echo sprintf('%.2f',$value['market_cup']);?></td>
                 <td><?php echo sprintf('%.2f',$value['ttm']);?></td>
                 <td><?php echo $value['report_year'].$value['report_type'];?></td>
                 <td><?php echo $value['release_date'];?></td>
             </tr>
             <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
    $totalPage = ceil($total_num/$countPerPage);
    $pageSeq = array();
    if($totalPage <= 7) {
        for($i=1;$i<=$totalPage;$i++){
            $pageSeq[$i-1] = $i;
        }
    }
    else {
        if($page <= 3 || $page >= $totalPage - 2) {
            $pageSeq = array(1,2,3,'...',$totalPage-2,$totalPage-1,$totalPage);
        }
        else {
            $pageSeq = array(1,'...',$page-1,$page,$page+1,'...',$totalPage);
        }
    }
    if($page != 'all'):
?>
<div class="company-list-page">
    <ul class="pagination text-center" role="navigation" aria-label="Pagination">
        <?php if($page==1): ?>
        <li class="pagination-previous disabled">上一页</li>
        <?php else: ?>
        <li class="pagination-previous"><a href="javascript:void(0)" id="list_page_pre">上一页</a></li>
        <?php endif; ?>
        <!--<li class="current"><span class="show-for-sr">当前:&nbsp;</span> 1</li>-->
        <?php for($i=0;$i<count($pageSeq);$i++): ?>
        <li>
            <?php if($pageSeq[$i] !='...'):?>
            <a href="javascript:void(0)" class="<?php if($page==$pageSeq[$i])echo "current";?> list_page_num"><?php echo $pageSeq[$i];?></a>
            <?php else: ?>
            ...
            <?php endif; ?>
        </li>
        <?php endfor; ?>
        <?php if($page==$totalPage): ?>
        <li class="pagination-next disabled">下一页</li>
        <?php else: ?>
        <li class="pagination-next"><a href="javascript:void(0)" id="list_page_next">下一页</a></li>
        <?php endif; ?>
    </ul>
</div>
<?php endif; ?>
