<script type="text/javascript" src="//d3js.org/d3.v3.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/cal-heatmap/3.3.11/cal-heatmap.min.js"></script>
<script type="text/javascript" src="http://momentjs.com/downloads/moment-with-locales.min.js"></script>
<link rel="stylesheet" href="../css/cal-heatmap.css" />
<div class="index-body">
    <div class="row">
        <div class="index-cal-body">
            <div class="small-1 columns index-cal-arrow-body"><button id="cal_left"><img src="../images/arrow_left.png" /></button></div>
            <div class="small-10 columns" id="test2"></div>
            <div class="small-1 columns index-cal-arrow-body" style="text-align:right"><button id="cal_right"><img src="../images/arrow_right.png" /></button></div>
        </div>
    </div>
    <div class="row">
        <div class="index-cal-selector">
            <div class="small-1 columns"><button class="left"><img src="../images/arrow_left.png" /></button></div>
            <div class="small-10 columns">
                <div class="row small-up-7">
                    <div class="column index-cal-selector-title" id="cal_selector_1">
                        <div>周一</div>
                        <div class="date"></div>
                    </div>
                    <div class="column index-cal-selector-title" id="cal_selector_2">
                        <div>周二</div>
                        <div class="date"></div>
                    </div>
                    <div class="column index-cal-selector-title" id="cal_selector_3">
                        <div>周三</div>
                        <div class="date"></div>
                    </div>
                    <div class="column index-cal-selector-title" id="cal_selector_4">
                        <div>周四</div>
                        <div class="date"></div>
                    </div>
                    <div class="column index-cal-selector-title" id="cal_selector_5">
                        <div>周五</div>
                        <div class="date"></div>
                    </div>
                    <div class="column index-cal-selector-title" id="cal_selector_6">
                        <div>周六</div>
                        <div class="date"></div>
                    </div>
                    <div class="column index-cal-selector-title" id="cal_selector_7">
                        <div>周日</div>
                        <div class="date"></div>
                    </div>
                </div>
            </div>
            <div class="small-1 right columns"><button class="right"><img src="../images/arrow_right.png" /></button></div>
        </div>
    </div>
    <div class="row">
        <div class="index-industry-seletor">
            <div class="small-2 left columns">行业:&nbsp;<span class="index-industry-list-title" type="button" id="industry_title" data-toggle="industry_dropdown">全部&nbsp;&#9660;</span></div>
            <div class="small-4 left columns">子行业:&nbsp;<span class="index-industry-list-title" type="button" id="subindustry_title" data-toggle="subindustry_dropdown">全部&nbsp;&#9660;</span></div>
            <div class="small-4 right columns" style="text-align:right"><input type='checkbox' />&nbsp;仅包括沪深300指数成分股</div>
        </div>
        <div class="dropdown-pane bottom index-industry-list" id="industry_dropdown" data-dropdown >
            <ul>
                <li>全部</li>
                <?php foreach($industry_data as $key=>$value): ?>
                <li class="industry_list_select" sub='<?php echo json_encode($value['sub']);?>'><?php echo $value['name'];?></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="dropdown-pane index-industry-list" id="subindustry_dropdown" data-dropdown >
            <ul id="subindustry_list">
                <li>全部</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="index-table-block">
            <div>符合条件的股票:&nbsp;?个</div>
            <div>
                <table class="index-table-list">
                    <tbody>
                        <tr>
                            <th>test</th>
                            <th>test</th>
                            <th>test</th>
                            <th>test</th>
                        </tr>
                        <?php for($i=0;$i<7;$i++): ?>
                        <tr>
                            <td>test</td>
                            <td>test</td>
                            <td>test</td>
                            <td>test</td>
                        </tr>
                        <?php endfor; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>    
<script>
    $(document).foundation();
</script>
<script src="../js/index.js" type='text/javascript'></script>
